### ISSUE TITLE
Forking your code

### ISSUE THREAD

**Issue by mochang** [Chuckland/sketch-number-artboards#1]
Hi,
I made some changes to your original code to fit my workflow. I used your code for numbering artboards as the base and made modifications from there. I am going to make the repo publicly available and I will ensure that you are credited in the readme and in comments in the code itself. Is it okay if I go ahead and  make the code public and credit you accordingly? Thanks so much for the great work.

Mo

**Comment by Chuckland** [comment]
Hi

> Is it okay if I go ahead and make the code public and credit you accordingly?

Yes. It's ok.
